#!/usr/bin/env bash

if [[ "$1" ]]; then
  pandoc $1 -o manuscript.pdf --pdf-engine=weasyprint \
  --css template/style.css --css template/fonts/font.css \
  --template=template/layout.html

  open manuscript.pdf
fi
